Repository akashsrikanth2310/TripSage, pull requests merged in 2020-10, with the labels that each got.

#28 User registration and authentication frontend
  TripSage/settings.py
  TripSage/urls.py
  templates/registration/login.html
  templates/registration/signup.html
  tripHome/static/css/bootsnav.css
  tripHome/static/css/style.css
  tripHome/templates/base_generic.html
  tripHome/templates/header.html
  tripHome/templates/index.html
  tripHome/templates/registration/signup.html
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: bug, engineering debt, enhancement, frontend

#31 User authentication - build errors resolving of PR#28
  TripSage/settings.py
  templates/registration/login.html
  templates/registration/signup.html
  tripHome/static/css/style.css
  tripHome/templates/base_generic.html
  tripHome/templates/footer.html
  tripHome/templates/header.html
  tripHome/templates/imports.html
  tripHome/templates/registration/login.html
  tripHome/templates/registration/signup.html
  users/admin.py
  users/apps.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: bug, frontend

#39 charlotte insights
  tripHome/templates/charlotteadventurous.html
  tripHome/templates/charlottekidfriendly.html
  tripHome/templates/charlotterelax.html
  tripHome/urls.py
  tripHome/views.py
Labels: frontend

#53 Updating formatting and correcting links provided in Contributing.MD
  CONTRIBUTING.md
Labels: documentation

#55 Updating Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#56 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#57 Updated setup with new details
  setup.py
Labels: documentation
